name: Run Python Tests

on: 
  push:
    branches:
      - 'main'  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      working-directory: pigeon-client/client
      run: poetry install

    - name: Run tests
      working-directory: pigeon-client/client
      run: poetry run python3 unit-tests.py
